### ISSUE TITLE
Unable to build the new boilerplate project on Xcode

### ISSUE THREAD

**Issue by saifullahsajid** [skiptools/skip#36]
Installation and all the setup was successful but when I try to build the project on Xcode it shows this error and I see no details about the error If I click it.

```swift
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by marcprux** [comment]
We released a new version (`0.7.18`) of skip that may address it. Can you `skip upgrade` and then make a new project (with `skip init --appid=com.xyz.App SomeProject` and let us know if that builds in Xcode?

If not, can you post the output of `skip checkup`? If it fails, please look at the output of `skip checkup -v` and let us know if you see any error messages in there.

We will close this issue for now, but please re-open with additional information.

**Comment by saifullahsajid** [comment]
@marcprux I upgraded to version `0.7.21`, created a new project, and tried running it but I still faced the same issue. Here is my `skip checkup`
<img width="421" alt="Screenshot 2023-11-07 at 8 43 04 PM" src="https://github.com/skiptools/skip/assets/18142681/34aa7abf-35cc-48af-b236-d9e5167e8aef">
